spring.application.name=admision


spring.datasource.url=jdbc:postgresql://localhost:5432/UNICA
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080

app.storage.excels=uploads/excels
app.storage.pdfs=uploads/pdfs

app.storage.evidencias=uploads/evidencias
app.storage.imagenes=uploads/imagenes

# Carga masiva del banco de preguntas
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
